<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.9" tiledversion="1.9.2" name="Tileset3" tilewidth="32" tileheight="32" tilecount="200" columns="20">
 <image source="Tileset.png" width="640" height="320"/>
 <tile id="0" class="Руда"/>
 <tile id="1" class="Руда"/>
 <tile id="2" class="Руда"/>
 <tile id="3" class="Руда"/>
 <tile id="4" class="Руда"/>
 <tile id="5" class="Поверхность"/>
 <tile id="6" class="Поверхность"/>
 <tile id="7" class="Поверхность"/>
 <tile id="8" class="Поверхность"/>
 <tile id="9" class="Поверхность"/>
 <tile id="10" class="Поверхность"/>
 <tile id="11" class="Препятствие"/>
 <tile id="12" class="Препятствие"/>
 <tile id="13" class="Препятствие"/>
 <tile id="14" class="Препятствие"/>
 <tile id="15" class="Поверхность"/>
 <tile id="16" class="Поверхность"/>
 <tile id="17" class="Поверхность"/>
 <tile id="18" class="Поверхность"/>
 <tile id="19" class="Поверхность"/>
 <tile id="20" class="Руда"/>
 <tile id="21" class="Руда"/>
 <tile id="22" class="Руда"/>
 <tile id="23" class="Руда"/>
 <tile id="24" class="Руда"/>
 <tile id="25" class="Поверхность"/>
 <tile id="26" class="Поверхность"/>
 <tile id="27" class="Поверхность"/>
 <tile id="28" class="Поверхность"/>
 <tile id="29" class="Поверхность"/>
 <tile id="30" class="Поверхность"/>
 <tile id="31" class="Препятствие"/>
 <tile id="32" class="Препятствие"/>
 <tile id="33" class="Препятствие"/>
 <tile id="34" class="Препятствие"/>
 <tile id="35" class="Поверхность"/>
 <tile id="36" class="Поверхность"/>
 <tile id="37" class="Поверхность"/>
 <tile id="38" class="Поверхность"/>
 <tile id="39" class="Поверхность"/>
 <tile id="40" class="Руда"/>
 <tile id="41" class="Руда"/>
 <tile id="42" class="Руда"/>
 <tile id="43" class="Руда"/>
 <tile id="44" class="Руда"/>
 <tile id="45" class="Поверхность"/>
 <tile id="46" class="Поверхность"/>
 <tile id="47" class="Поверхность"/>
 <tile id="48" class="Поверхность"/>
 <tile id="49" class="Поверхность"/>
 <tile id="50" class="Поверхность"/>
 <tile id="51" class="Препятствие"/>
 <tile id="52" class="Поверхность"/>
 <tile id="53" class="Препятствие"/>
 <tile id="55" class="Поверхность"/>
 <tile id="56" class="Поверхность"/>
 <tile id="57" class="Поверхность"/>
 <tile id="58" class="Поверхность"/>
 <tile id="59" class="Поверхность"/>
 <tile id="60" class="Руда"/>
 <tile id="61" class="Руда"/>
 <tile id="62" class="Руда"/>
 <tile id="63" class="Руда"/>
 <tile id="64" class="Руда"/>
 <tile id="65" class="Вода"/>
 <tile id="66" class="Поверхность"/>
 <tile id="67" class="Поверхность"/>
 <tile id="68" class="Поверхность"/>
 <tile id="69" class="Поверхность"/>
 <tile id="70" class="Поверхность"/>
 <tile id="71" class="Препятствие"/>
 <tile id="72" class="Препятствие"/>
 <tile id="73" class="Препятствие"/>
 <tile id="75" class="Поверхность"/>
 <tile id="76" class="Поверхность"/>
 <tile id="77" class="Поверхность"/>
 <tile id="78" class="Поверхность"/>
 <tile id="79" class="Поверхность"/>
 <tile id="86" class="Поверхность"/>
 <tile id="87" class="Поверхность"/>
 <tile id="88" class="Поверхность"/>
 <tile id="89" class="Поверхность"/>
 <tile id="90" class="Поверхность"/>
 <tile id="91" class="Поверхность"/>
 <tile id="95" class="Поверхность"/>
 <tile id="96" class="Поверхность"/>
 <tile id="97" class="Поверхность"/>
 <tile id="98" class="Поверхность"/>
 <tile id="99" class="Поверхность"/>
</tileset>
